"""Add assignee column to Todo table

Revision ID: 54186d70496d
Revises: 
Create Date: 2023-03-31 20:45:47.949888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54186d70496d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assignee', sa.String(length=10), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.drop_column('assignee')

    # ### end Alembic commands ###
